# Generated by Django 2.2 on 2019-09-27 08:50

import autoslug.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('website', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('middle', models.CharField(blank=True, max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('desc', markdownx.models.MarkdownxField(blank=True, max_length=1000)),
                ('photo', models.ImageField(null=True, upload_to='authors/images/%Y/%m/%d')),
                ('orcid', models.CharField(max_length=19, null=True)),
                ('pgp', models.CharField(max_length=50, null=True)),
                ('twitter', models.CharField(max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=150, populate_from='full_name')),
                ('vita', models.FileField(blank=True, default='', upload_to='authors/vitae/')),
            ],
        ),
        migrations.CreateModel(
            name='BathContours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('depth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CitationStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('file', models.FileField(upload_to='citestyles/')),
            ],
        ),
        migrations.CreateModel(
            name='ElevContours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('elev', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='UrbanArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', markdownx.models.MarkdownxField()),
                ('timestamp', models.DateTimeField()),
                ('content_type', models.CharField(max_length=150)),
                ('banner', models.ImageField(null=True, upload_to='posts/banners/%Y/%m/%d')),
                ('bib', models.FileField(null=True, upload_to='bibs/')),
                ('attach', models.FileField(blank=True, default='', upload_to='attachments/')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=150, null=True, populate_from='title')),
                ('authors', models.ManyToManyField(to='blog.Author')),
                ('csl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.CitationStyle')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt', models.CharField(max_length=150, null=True)),
                ('inst', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('affiliates', models.ManyToManyField(through='blog.Affiliation', to='blog.Author')),
            ],
        ),
        migrations.AddField(
            model_name='affiliation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Institution'),
        ),
    ]
