# Generated by Django 2.2 on 2019-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='page',
            field=models.BooleanField(default=False),
        ),
    ]
