# Generated by Django 2.1.7 on 2021-02-16 03:17

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210215_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/%Y/%m/%d')),
                ('day', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('title', models.CharField(max_length=100)),
                ('desc', markdownx.models.MarkdownxField()),
                ('virtual_url', models.URLField(blank=True, default='')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ticket_url', models.URLField(blank=True, default='')),
                ('cancel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('D', 'Discussant'), ('M', 'Moderator'), ('P', 'Panelist'), ('L', 'Lecturer'), ('I', 'Introducer'), ('W', 'Workshop Leader')], default='L', max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(through='blog.Role', to='blog.Author'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Institution'),
        ),
    ]
