# Generated by Django 2.1.7 on 2021-02-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210215_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Institution'),
        ),
    ]
