# Generated by Django 2.1.7 on 2021-02-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210215_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ManyToManyField(blank=True, to='blog.Institution'),
        ),
    ]
