# Generated by Django 2.1.7 on 2021-02-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210215_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('D', 'Discussant'), ('M', 'Moderator'), ('P', 'Panelist'), ('R', 'Presenter'), ('I', 'Introducer'), ('W', 'Workshop Leader')], default='L', max_length=1),
        ),
    ]
