# Generated by Django 2.1.7 on 2021-02-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210215_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_url',
        ),
    ]
