# Generated by Django 2.1.7 on 2021-02-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210215_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
