# Generated by Django 2.1.7 on 2021-03-15 15:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210315_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee_Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department_Lab_Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, default='')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField(null=True)),
                ('terminal', models.BooleanField(default=False)),
                ('concentration', models.CharField(blank=True, max_length=150)),
                ('desc', markdownx.models.MarkdownxField(blank=True)),
                ('show', models.BooleanField(default=True)),
                ('degree', models.CharField(blank=True, choices=[('MCP', 'Master of City Planning'), ('PhD', 'Doctor of Philosophy'), ('MUP', 'Master of Urban Planning'), ('MURP', 'Master of Urban and Regional Planning'), ('MFA', 'Master of Fine Arts'), ('MLA', 'Master of Landscape Architecture'), ('MArch', 'Master of Architecture'), ('MBA', 'Master of Business Administration'), ('MPA', 'Master of Public Administration'), ('MDes', 'Master of Design Studies'), ('DDes', 'Doctor of Design'), ('BFA', 'Bachelor of Fine Arts'), ('BA', 'Bachelor of Arts'), ('BS', 'Bachelor of Science'), ('GC', 'Graduate Certificate'), ('UC', 'Undergraduate Certificate'), ('', 'None')], default='', max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='affiliation',
            old_name='author',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='inst',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='dpt',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='desc',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='kind',
            field=models.CharField(blank=True, choices=[('App', 'Appointment'), ('Aff', 'Affiliation'), ('', 'None')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='affil',
            field=models.ManyToManyField(through='blog.Affiliation', to='blog.Department_Lab_Center'),
        ),
        migrations.AddField(
            model_name='education',
            name='committee',
            field=models.ManyToManyField(through='blog.Committee_Membership', to='blog.Person'),
        ),
        migrations.AddField(
            model_name='committee_membership',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Education'),
        ),
        migrations.AddField(
            model_name='committee_membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Person'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='department_lab_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Department_Lab_Center'),
        ),
    ]
