# Generated by Django 2.1.7 on 2021-03-15 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210315_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department_lab_center',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='department_lab_center',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Institution'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ManyToManyField(blank=True, to='blog.Institution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(help_text='Name of the institution.', max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='affil',
            field=models.ManyToManyField(through='blog.Affiliation', to='blog.Institution'),
        ),
        migrations.DeleteModel(
            name='Department_Lab_Center',
        ),
    ]
