# Generated by Django 2.1.7 on 2021-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_institution_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='room',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
