# Generated by Django 2.1.7 on 2021-03-15 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210315_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Institution'),
        ),
    ]
