# Generated by Django 2.1.7 on 2021-03-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210315_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
