# Generated by Django 2.1.7 on 2021-03-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210315_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
