# Generated by Django 2.1.7 on 2021-03-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_event_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliation',
            options={'verbose_name': 'Affiliation', 'verbose_name_plural': 'Affiliation'},
        ),
        migrations.AlterModelOptions(
            name='citationstyle',
            options={'verbose_name': 'Citation Style', 'verbose_name_plural': 'Citation Styles'},
        ),
        migrations.AlterModelOptions(
            name='committee_membership',
            options={'verbose_name': 'Committee Membership', 'verbose_name_plural': 'Committee Memberships'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Periods of Education'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
    ]
