# Generated by Django 3.1.7 on 2021-03-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_education_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
