# Generated by Django 3.1.7 on 2021-03-15 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_person_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, choices=[('MCP', 'M. City Planning'), ('PhD', 'Ph.D.'), ('MUP', 'M. Urban Planning'), ('MURP', 'M. Urban and Regional Planning'), ('MFA', 'M. Fine Arts'), ('MLA', 'M. Landscape Architecture'), ('MArch', 'M. Architecture'), ('MBA', 'M. Business Administration'), ('MPA', 'M. Public Administration'), ('MDes', 'M. Design Studies'), ('DDes', 'D.Des.'), ('BFA', 'B. Fine Arts'), ('BA', 'B. Arts'), ('BS', 'B. Science'), ('GC', 'Graduate Certificate'), ('UC', 'Undergraduate Certificate'), ('', 'None')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='cred',
            field=models.CharField(blank=True, choices=[('MCP', 'M. City Planning'), ('PhD', 'Ph.D.'), ('MUP', 'M. Urban Planning'), ('MURP', 'M. Urban and Regional Planning'), ('MFA', 'M. Fine Arts'), ('MLA', 'M. Landscape Architecture'), ('MArch', 'M. Architecture'), ('MBA', 'M. Business Administration'), ('MPA', 'M. Public Administration'), ('MDes', 'M. Design Studies'), ('DDes', 'D.Des.'), ('', 'None')], default='', max_length=5),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the award.', max_length=200)),
                ('kind', models.CharField(blank=True, choices=[('A', 'Awards and Honors'), ('F', 'Funding'), ('', 'None')], default='', max_length=3)),
                ('amount', models.IntegerField(null=True)),
                ('currency', models.CharField(blank=True, choices=[('CAD', 'Canadian Dollar'), ('USD', 'United States Dollar'), ('', 'None')], default='', max_length=3)),
                ('show', models.BooleanField(default=True)),
                ('grantees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grantee', to='blog.institution')),
                ('grantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grantor', to='blog.institution')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
            },
        ),
    ]
