# Generated by Django 3.1.7 on 2021-03-15 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20210315_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
