# Generated by Django 3.1.7 on 2021-03-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20210315_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='currency',
            field=models.CharField(blank=True, choices=[('CAD', 'Canadian Dollar'), ('USD', 'United States Dollar')], default='USD', max_length=3),
        ),
        migrations.RemoveField(
            model_name='award',
            name='grantees',
        ),
        migrations.AddField(
            model_name='award',
            name='grantees',
            field=models.ManyToManyField(blank=True, to='blog.Institution'),
        ),
    ]
