# Generated by Django 3.1.7 on 2021-03-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20210315_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
