# Generated by Django 3.1.7 on 2021-03-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20210316_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_type',
            new_name='content_kind',
        ),
    ]
