# Generated by Django 3.1.7 on 2021-03-19 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0035_auto_20210318_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_kind',
            new_name='attach_kind',
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='post',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
