# Generated by Django 3.1.7 on 2021-03-19 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20210319_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='main',
        ),
        migrations.RemoveField(
            model_name='post',
            name='csl',
        ),
        migrations.CreateModel(
            name='SiteWideSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('csl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.citationstyle')),
                ('main_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.person')),
            ],
            options={
                'verbose_name': 'SiteWideSetting',
                'verbose_name_plural': 'SiteWideSettings',
            },
        ),
    ]
