# Generated by Django 3.1.7 on 2021-03-19 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20210319_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
