# Generated by Django 3.1.7 on 2021-03-19 19:49

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20210319_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='display_date',
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='desc',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Describe the affiliation.'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='end',
            field=models.DateField(blank=True, help_text='End of the affiliation \n            (past affiliations will not be displayed on the front-end).', null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(help_text='To which institution is the person affiliated?', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.institution'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='kind',
            field=models.CharField(blank=True, choices=[('App', 'Appointment'), ('Aff', 'Affiliation'), ('', 'None')], default='', help_text='Is this affiliation a formal (generally, paid) \n            appointment or an affiliation?', max_length=5),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='person',
            field=models.ForeignKey(help_text='To which person does this affiliation apply?', on_delete=django.db.models.deletion.CASCADE, to='blog.person'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='primary',
            field=models.BooleanField(default=False, help_text="Is this the person's primary affiliation?"),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='show',
            field=models.BooleanField(default=False, help_text='Should this affiliation appear on the front-end?'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='start',
            field=models.DateField(help_text='Start of the affiliation.'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='title',
            field=models.CharField(blank=True, help_text="What is the person's title?", max_length=150),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='website',
            field=models.URLField(blank=True, help_text='What is the website _connected to this affiliation_?'),
        ),
        migrations.AlterField(
            model_name='award',
            name='amount',
            field=models.IntegerField(blank=True, help_text='The amount of money awarded, in its given currency (see next field).', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='currency',
            field=models.CharField(blank=True, choices=[('CAD', 'Canadian Dollar'), ('USD', 'United States Dollar')], default='USD', help_text='The currency in which the award/grant is given.', max_length=3),
        ),
        migrations.AlterField(
            model_name='award',
            name='end',
            field=models.DateField(blank=True, help_text='End of the award term.', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='grantees',
            field=models.ManyToManyField(blank=True, help_text='All institutions who received the award/grant.', to='blog.Institution'),
        ),
        migrations.AlterField(
            model_name='award',
            name='grantor',
            field=models.ForeignKey(help_text='All institutions who received the award/grant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grantor', to='blog.institution'),
        ),
        migrations.AlterField(
            model_name='award',
            name='kind',
            field=models.CharField(blank=True, choices=[('A', 'Awards and Honors'), ('F', 'Funding'), ('', 'None')], default='', help_text='Make the distinction between funding and awards/honors.', max_length=3),
        ),
        migrations.AlterField(
            model_name='award',
            name='show',
            field=models.BooleanField(default=True, help_text='Indicates the visibility of this award on the frontend.'),
        ),
        migrations.AlterField(
            model_name='award',
            name='start',
            field=models.DateField(help_text='Start of the award term.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Post content (can include Pandoc citations \n            if they appear in the bibliography).'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Post title (up to 150 chars).', max_length=150),
        ),
    ]
