# Generated by Django 3.1.7 on 2021-03-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20210319_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitewidesetting',
            name='main_bibliography',
            field=models.IntegerField(blank=True, help_text='Which person is the focus of this site?', null=True),
        ),
        migrations.AddField(
            model_name='sitewidesetting',
            name='main_bibliography_type',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('group', 'Group'), ('', 'None')], default='', help_text='Of what type is this bibliography?', max_length=5),
        ),
    ]
