# Generated by Django 3.1.7 on 2021-03-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20210321_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitewidesetting',
            name='main_bibliography_collection',
            field=models.CharField(blank=True, help_text='Which person is the focus of this site?', max_length=50, null=True),
        ),
    ]
