# Generated by Django 3.1.7 on 2021-03-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20210321_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitewidesetting',
            name='main_bibliography',
            field=models.IntegerField(blank=True, help_text='What is the Zotero ID of the site bibliography?', null=True),
        ),
        migrations.AlterField(
            model_name='sitewidesetting',
            name='main_bibliography_collection',
            field=models.CharField(blank=True, help_text='Is this bibliography a specific collection?', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitewidesetting',
            name='main_bibliography_file',
            field=models.FileField(blank=True, default='', help_text='Auto-updated bibliography file.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sitewidesetting',
            name='main_bibliography_version',
            field=models.IntegerField(blank=True, help_text='Auto-updated bibliography version.', null=True),
        ),
    ]
