# Generated by Django 3.1.7 on 2021-03-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20210321_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of this library.', max_length=100)),
                ('zotero_id', models.IntegerField(blank=True, help_text='What is the Zotero ID of the site bibliography?', null=True)),
                ('kind', models.CharField(blank=True, choices=[('user', 'User'), ('group', 'Group'), ('', 'None')], default='', help_text='Of what kind is this library?', max_length=5)),
                ('collection', models.CharField(blank=True, help_text="Specific subcollection id. (N.b., these don't version well.)", max_length=50, null=True)),
                ('version', models.IntegerField(blank=True, help_text='Auto-updated bibliography version.', null=True)),
                ('bib_file', models.FileField(blank=True, default='', help_text='Auto-updated bibliography file.', upload_to='')),
            ],
            options={
                'verbose_name': 'Zotero Library',
                'verbose_name_plural': 'Zotero Libraries',
            },
        ),
        migrations.AddField(
            model_name='sitewidesetting',
            name='library',
            field=models.ForeignKey(blank=True, help_text='What Zotero library should this use?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.library'),
        ),
    ]
