# Generated by Django 3.1.7 on 2021-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20210322_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='edu',
            field=models.ManyToManyField(help_text="List of person's current and historical education.", to='blog.Education'),
        ),
    ]
