# Generated by Django 3.1.7 on 2021-03-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_person_edu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='edu',
        ),
        migrations.AddField(
            model_name='education',
            name='person',
            field=models.ForeignKey(help_text="List of person's current and historical education.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help', to='blog.person'),
        ),
    ]
