# Generated by Django 3.1.7 on 2021-03-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_auto_20210322_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='pi_awardee',
            field=models.ForeignKey(help_text='P.I. or awardee.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.person'),
        ),
    ]
