# Generated by Django 3.1.7 on 2021-03-23 12:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_award_pi_awardee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Approximate location of institution.', null=True, srid=4326),
        ),
    ]
