# Generated by Django 3.1.7 on 2021-03-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20210323_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='postal',
            field=models.CharField(blank=True, default='', help_text='Postcode in which institution is located.', max_length=20),
        ),
    ]
