# Generated by Django 3.1.7 on 2021-03-31 13:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_auto_20210323_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateField(help_text='On what day does the conference start?')),
                ('end', models.DateField(help_text='On what day does the conference end?')),
                ('virtual', models.BooleanField(default=False, help_text='Check this box if the conference is virtual.')),
                ('website', models.URLField(blank=True, default='', help_text='Provide a link to the conference website.')),
                ('address', models.CharField(blank=True, default='', help_text='Address of the institution.', max_length=200)),
                ('city', models.CharField(help_text='City in which institution is located.', max_length=100)),
                ('state', models.CharField(help_text='State in which institution is located.', max_length=100)),
                ('postal', models.CharField(blank=True, default='', help_text='Postcode in which institution is located.', max_length=20)),
                ('country', models.CharField(help_text='Country in which institution is located.', max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Approximate location of institution.', null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
            },
        ),
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='sponsors',
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('O', 'Organizer'), ('D', 'Discussant'), ('M', 'Moderator'), ('P', 'Panelist'), ('R', 'Presenter'), ('I', 'Introducer'), ('W', 'Workshop Leader')], default='L', help_text="What is the person's role in the event?", max_length=1),
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="What is the event's title?", max_length=100)),
                ('organizations', models.ManyToManyField(blank=True, help_text='Associated professional orgs?', to='blog.Institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='conference',
            field=models.ForeignKey(blank=True, default='', help_text='Is the event part of a conference?', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.conferenceinstance'),
        ),
    ]
