# Generated by Django 3.1.7 on 2021-03-31 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_auto_20210331_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenceinstance',
            options={'verbose_name': 'Conference Instance', 'verbose_name_plural': 'Conferences Instances'},
        ),
        migrations.AddField(
            model_name='conferenceinstance',
            name='conference',
            field=models.ForeignKey(blank=True, default='', help_text='Which conference is this a part of?', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.conference'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, help_text='What are the sponsoring institutions?', to='blog.Institution'),
        ),
    ]
